name: magic-ninja
service:
  port: 80
  targetPort: 3000
  type: NodePort
  host: spacechat.lol
  tag: f6ca222d841e5d9c2ca16517bca23ca5a26419ef
  image: ghcr.io/sorjak/spacechat
env:
  SPACECHAT_SERVER_HOST: spacechat.lol
  SPACECHAT_SERVER_PORT: 3000 # the port that the server runs on, inside the container
  SPACECHAT_SERVER_PROTOCOL: https

  SPACECHAT_CLIENT_PORT: 443 # used on the mobile client to connect to websocket server

  SPACECHAT_SERVER_TRAITOR_CUTOFF: 6
  SPACECHAT_SERVER_MAX_PLAYERS: 32
  SPACECHAT_SERVER_UPDATE_TICK: 150
  SPACECHAT_SERVER_HEARTBEAT_TICK: 20000
