name: magic-ninja
service:
  port: 80
  targetPort: 3001
  type: NodePort
  host: game.spacechat.lol
  tag: f6ca222d841e5d9c2ca16517bca23ca5a26419ef
  image: ghcr.io/sorjak/spacechat
env:
  SERVER_PORT: '3001'
